title: WikiTest
description: A starter template for a Jeykll site hosting SiliPedia
theme: just-the-docs

url: https://danielthurmond.github.io/SiliPedia

search_enabled: true #enable built-in searchbar for finding wiki pages

aux_links:
  Template Repository: https://github.com/danielthurmond/SiliPedia
